//savannah players
const savannah = [
    {
        number: "1",
        firstName: "Bill",
        lastName: "LeRoy",
        position: "C",
        photo: "savannah/LeRoy.jpeg",
        talentName: "The Self-Introducer",
    },
    {
        number: "2",
        firstName: "Reese",
        lastName: "Alexiades",
        position: "OF",
        photo: "savannah/Alexiades.jpeg",
        talentName: "The Caped Crusader",
    },
    {
        number: "3",
        firstName: "Bryce",
        lastName: "Grizzaffi",
        position: "C",
        photo: "savannah/Grizzaffi.jpeg",
        talentName: "The Louisiana Drip ",
    },
    {
        number: "4",
        firstName: "KJ",
        lastName: "Jackson",
        position: "UTL",
        photo: "savannah/KJ.jpeg",
        talentName: "The 5-Position Dancer",
    },
    {
        number: "5",
        firstName: "DR",
        lastName: "Meadows",
        position: "OF",
        photo: "savannah/Meadows.jpeg",
        talentName: "The Outfield Flipper",
    },
    {
        number: "6",
        firstName: "Ryan",
        lastName: "Cox",
        position: "SS",
        photo: "savannah/Cox.jpeg",
        talentName: "The Glove Machine",
    },
    {
        number: "7",
        firstName: "Ty",
        lastName: "Jackson",
        position: "OF",
        photo: "savannah/Ty.jpeg",
        talentName: "The Hype Machine",
    },
    {
        number: "8",
        firstName: "Jackson",
        lastName: "Olson",
        position: "INF",
        photo: "savannah/Olson.jpeg",
        talentName: "The Content King",
    },
    {
        number: "9",
        firstName: "Max",
        lastName: "Jung-Goldberg",
        position: "UTL",
        photo: "savannah/Jung-Goldberg.jpeg",
        talentName: "The Bougie Bomber",
    },
    {
        number: "10",
        firstName: "Alex",
        lastName: "Ziegler",
        position: "1B",
        photo: "savannah/Ziegler.jpeg",
        talentName: "The Bat Spinner",
    },
    {
        number: "11",
        firstName: "Austin",
        lastName: "Drury",
        position: "P",
        photo: "savannah/Drury.jpeg",
        talentName: "The Tumbling Handoff",
    },
    {
        number: "12",
        firstName: "Kyle",
        lastName: "Luigs",
        position: "P",
        photo: "savannah/Luigs.jpeg",
        talentName: "The Fireballer",
    },
    {
        number: "13",
        firstName: "Bryce",
        lastName: "Stober",
        position: "Assistant Coach",
        photo: "savannah/Stober.jpeg",
        talentName: "The Tactical Mastermind",
    },
    {
        number: "14",
        firstName: "Dakota",
        lastName: "Albritton",
        position: "UTL",
        photo: "savannah/Albritton.jpeg",
        talentName: "The 10-Foot Giant",
    },
    {
        number: "15",
        firstName: "RobertAnthony",
        lastName: "Cruz",
        position: "OF",
        photo: "savannah/Cruz.jpeg",
        talentName: "Coach RAC",
    },
    {
        number: "16",
        firstName: "Adam",
        lastName: "Virant",
        position: "Coach",
        photo: "savannah/Virant.jpeg",
        talentName: "The Logistics General",
    },
    {
        number: "17",
        firstName: "Easton",
        lastName: "Parrish",
        position: "C",
        photo: "savannah/Parrish.jpeg",
        talentName: "The Trick Handoff",
    }, {
        number: "18",
        firstName: "Danny",
        lastName: "Hosley",
        position: "UTL",
        photo: "savannah/Hosley.jpeg",
        talentName: "The Ironman",
    }, {
        number: "19",
        firstName: "Dan",
        lastName: "Oberst",
        position: "DH",
        photo: "savannah/Oberst.jpeg",
        talentName: "The Mirror Talker",
    }, {
        number: "20",
        firstName: "Grant",
        lastName: "Besser",
        position: "P",
        photo: "savannah/Besser.jpeg",
        talentName: "The Choreographed Twins",
    }, {
        number: "21",
        firstName: "Jacob",
        lastName: "Bazala",
        position: "P",
        photo: "savannah/Bazala.jpeg",
        talentName: "The Choreographed Twins",
    }, {
        number: "22",
        name: "JT Sokolove",
        position: "DR",
        photo: "savannah/Sokolove.jpeg",
        talentName: "The Base Bandit",
    }, {
        number: "23",
        firstName: "Reginald",
        lastName: "Horton",
        position: "Inspiration Coach",
        photo: "savannah/Horton.jpeg",
        talentName: "The Soul Coach",
    }, {
        number: "24",
        firstName: "Derek",
        lastName: "Klena",
        position: "RHP",
        photo: "savannah/Klena.jpeg",
        talentName: "The Broadway Belter",
    }, {
        number: "30",
        firstName: "Connor",
        lastName: "Harris",
        position: "P",
        photo: "savannah/Harris.jpeg",
        talentName: "The Skit Pitchers",
    }, {
        number: "31",
        firstName: "Trystan",
        lastName: "Levesque",
        position: "P",
        photo: "savannah/Levesque.jpeg",
        talentName: "The Skit Pitchers",
    }, {
        number: "33",
        firstName: "Kelsie",
        lastName: "Whitmore",
        position: "P",
        photo: "savannah/Whitmore.jpeg",
        talentName: "The Trailblazer",
    }, {
        number: "44",
        firstName: "Allan",
        lastName: "Saathoff",
        position: "P",
        photo: "savannah/Saathoff.jpeg",
        talentName: "The Fireman",
    }, {
        number: "49",
        firstName: "Ryan",
        lastName: "Kellogg",
        position: "P Coach",
        photo: "savannah/Kellogg.jpeg",
        talentName: "Big Maple",
    }, {
        number: "66",
        firstName: "Tyler",
        lastName: "Gillum",
        position: "Head Coach",
        photo: "savannah/Gillum.jpeg",
        funFact: "Excellent Breakfast Chef",
        talentName: "The Mastermind",
    }, {
        number: "88",
        firstName: "Noah",
        lastName: "Niznik",
        position: "P",
        photo: "savannah/Niznik.jpeg",
        funFact: "Loves Mariah Carey",
        talentName: "The Mariah Carey Fan",
    }, {
        number: "99",
        firstName: "Frankie",
        lastName: "Moscatiello",
        position: "P",
        photo: "savannah/Moscatiello.jpeg",
        funFact: "Excellent Breakfast Chef",
        talentName: "The Lock-Down Closer",
    },
];


//party players
const party = [
    {
        number: "0",
        firstName: "Thomas",
        lastName: "Simoneaux",
        position: "Coach",
        photo: "party/Simoneaux.jpeg",
        talentName: "The Routine Coordinator",
    },
    {
        number: "1",
        firstName: "Ashton",
        lastName: "Lansdell",
        position: "2B",
        photo: "party/Lansdell.jpeg",
        talentName: "THe Groundbreaker",
    },
    {
        number: "2",
        firstName: "Jason",
        lastName: "Swan",
        position: "1B",
        photo: "party/Swan.jpeg",
        talentName: "The Dance Machine Firstman",
    },
    {
        number: "3",
        firstName: "TJ",
        lastName: "Reeves",
        position: "OF",
        photo: "party/Reeves.jpeg",
        talentName: "The Long-Ball Lunatic",
    },
    {
        number: "4",
        firstName: "Tanner",
        lastName: "Thomas",
        position: "OF",
        photo: "party/Thomas.jpeg",
        talentName: "The Airtime Artist",
    },
    {
        number: "5",
        firstName: "Andy",
        lastName: "Cosgrove",
        position: "C",
        photo: "party/Cosgrove.jpeg",
        talentName: "The Choreograpgy Catcher",
    },
    {
        number: "6",
        firstName: "Reece",
        lastName: "Hampton",
        position: "OF",
        photo: "party/Hampton.jpeg",
        talentName: "The Jet-Fuel Sprinter",
    },
    {
        number: "7",
        firstName: "Mike",
        lastName: "Vavasis",
        position: "Head Coach",
        photo: "party/Vavasis.jpeg",
        talentName: "The Party Mastermind",
    },
    {
        number: "8",
        firstName: "Bryson",
        lastName: "Bloomer",
        position: "3B",
        photo: "party/Bloomer.jpeg",
        talentName: "The COrner Showman",
    },
    {
        number: "9",
        firstName: "Dustin",
        lastName: "Baber",
        position: "2B",
        photo: "party/Baber.jpeg",
        talentName: "The Trick-Flip Infielder",
    },
    {
        number: "10",
        firstName: "Bret",
        lastName: "Helton",
        position: "RHP",
        photo: "party/Helton.jpeg",
        talentName: "The Heavy-Heater Righty",
    },
    {
        number: "11",
        firstName: "Chase",
        lastName: "Achuff",
        position: "SS",
        photo: "party/Achuff.jpeg",
        talentName: "The Glove Conductor",
    },
    {
        number: "12",
        firstName: "Noah",
        lastName: "Fisher",
        position: "UTL",
        photo: "party/Fisher.jpeg",
        talentName: "The Everywhere Utility",
    },
    {
        number: "13",
        firstName: "Brady",
        lastName: "Kais",
        position: "LHP",
        photo: "party/Kais.jpeg",
        talentName: "The Southpaw Striker",
    },
    {
        number: "15",
        firstName: "Dylan",
        lastName: "Porter",
        position: "RHP",
        photo: "party/Porter.jpeg",
        talentName: "The Mind-Game Reliever",
    },
    {
        number: "17",
        firstName: "Dalton",
        lastName: "Ponce",
        position: "RHP",
        photo: "party/Ponce.jpeg",
        talentName: "The High-Stakes Closer",
    },
    {
        number: "21",
        firstName: "Riyan",
        lastName: "Rodriguez",
        position: "RHP",
        photo: "party/Rodriguez.jpeg",
        talentName: "THe Chopped-Hair Fireballer",
    },
    {
        number: "22",
        firstName: "Peter",
        lastName: "Holden",
        position: "LHP",
        photo: "party/Holden.jpeg",
        talentName: "The Breaking-Ball Technician",
    },
    {
        number: "25",
        firstName: "Sean",
        lastName: "Fluke",
        position: "RHP",
        photo: "party/Fluke.jpeg",
        talentName: "The Mound Jester",
    },
    {
        number: "26",
        firstName: "Nate",
        lastName: "Tellier",
        position: "RHP",
        photo: "party/Tellier.jpeg",
        talentName: "The Velocity Thriller",
    },
    {
        number: "27",
        firstName: "Jake",
        lastName: "Lialios",
        position: "RHP",
        photo: "party/Lialios.jpeg",
        talentName: "The Delivery Chameleon",
    },
    {
        number: "28",
        firstName: "Drew",
        lastName: "Gillespie",
        position: "RHP",
        photo: "party/Gillespie.jpeg",
        talentName: "The CLean-Inning King",
    },
    {
        number: "40",
        firstName: "Mark",
        lastName: "Smith",
        position: "DR",
        photo: "party/Smith.jpeg",
        talentName: "The Pink Base Bandit",
    },
    {
        number: "41",
        firstName: "Bronson",
        lastName: "Balholm",
        position: "C",
        photo: "party/Balholm.jpeg",
        talentName: "The Plate Magician",
    },
    {
        number: "57",
        firstName: "Anthony",
        lastName: "Coromato",
        position: "Coach",
        photo: "party/Coromato.jpeg",
        talentName: "The Hype Architect",
    },
    {
        number: "407",
        firstName: "Michael",
        lastName: "Ballard",
        position: "IF",
        photo: "party/Ballard.jpeg",
        talentName: "THe Infield Anchor",
    },
    {
        number: "777",
        firstName: "Garrett",
        lastName: "Delano",
        position: "RHP",
        photo: "party/Delano.jpeg",
        talentName: "The 64-Second Sub",
    },
    {
        number: "999",
        firstName: "John-Howard",
        lastName: "Bobo",
        position: "UTL",
        photo: "party/Bobo.jpeg",
        talentName: "The Banana Rapper",
    },
    {
        number: "X",
        firstName: "Jake",
        lastName: "Skole",
        position: "OF",
        photo: "party/Skole.jpeg",
        talentName: "The Wildcard Outfielder",
    },
];

//firefighter players
const fire = [
    {
        number: "🔥",
        firstName: "Marshall",
        lastName: "Shill",
        position: "RHP",
        photo: "fire/Shill.jpeg",
        talentName: "The Fire Marshall",
    },
    {
        number: "0",
        firstName: "Lamar",
        lastName: "Sparks",
        position: "OF",
        photo: "fire/Sparks.jpeg",
        talentName: "The Scoreboard Hunter",
    },
    {
        number: "1",
        firstName: "Christian",
        lastName: "Dearman",
        position: "RHP",
        photo: "fire/Dearman.jpeg",
        talentName: "The First-Alarm Righty",
    },
    {
        number: "2",
        firstName: "Caden",
        lastName: "Green",
        position: "SS",
        photo: "fire/Green.jpeg",
        talentName: "The Vacuum Shortstop",
    },
    {
        number: "3",
        firstName: "Dalton",
        lastName: "Cornett",
        position: "C",
        photo: "fire/Cornett.jpeg",
        talentName: "The Flame-Catcher",
    },
    {
        number: "3.14",
        firstName: "Corey",
        lastName: "Pye",
        position: "Pitching Coach",
        photo: "fire/Pye.jpeg",
        talentName: "The Pi Tactician",
    },
    {
        number: "4",
        firstName: "Eric",
        lastName: "Jones Jr.",
        position: "C/1B",
        photo: "fire/Jones Jr..jpeg",
        talentName: "The Two-Alarm Anchor",
    },
    {
        number: "6",
        firstName: "Austin",
        lastName: "Temple",
        position: "RHP",
        photo: "fire/Temple.jpeg",
        talentName: "The Inferno Thrower",
    },
    {
        number: "7",
        firstName: "Mason",
        lastName: "Maxwell",
        position: "OF",
        photo: "fire/Maxwell.jpeg",
        talentName: "The House Tracker",
    },
    {
        number: "8",
        firstName: "South",
        lastName: "Trimble",
        position: "DR",
        photo: "fire/Trimble.jpeg",
        talentName: "The Dreamy Bandit",
    },
    {
        number: "9",
        firstName: "Noah",
        lastName: "Bridges",
        position: "OF",
        photo: "fire/Bridges.jpeg",
        talentName: "The Best-Hair Flycatcher",
    },
    {
        number: "10",
        firstName: "Darrien",
        lastName: "",
        position: "1B/OF",
        photo: "fire/Darrien.jpeg",
        talentName: "The Corner Extinguisher",
    },
    {
        number: "11",
        firstName: "Logan",
        lastName: "Lacey",
        position: "3B",
        photo: "fire/Lacey.jpeg",
        talentName: "The Hot-Corner Guard",
    },
    {
        number: "12",
        firstName: "Zachary",
        lastName: "Bridges",
        position: "C",
        photo: "fire/Bridges.jpeg",
        talentName: "The Bullet-Proof Backstop",
    },
    {
        number: "15",
        firstName: "Liam",
        lastName: "Spence",
        position: "INF",
        photo: "fire/Spence.jpeg",

        talentName: "",
    },
    {
        number: "16",
        firstName: "Drew",
        lastName: "Yniesta",
        position: "Assistant Coach",
        photo: "fire/Yniesta.jpeg",
        talentName: "The Rapid Transfer",
    },
    {
        number: "18",
        firstName: "Ben",
        lastName: "Dum III",
        position: "RHP",
        photo: "fire/Dum III.jpeg",
        talentName: "The Sinker Specialist",
    },
    {
        number: "21",
        firstName: "Jared",
        lastName: "Donalson",
        position: "RHP",
        photo: "fire/Donalson.jpeg",
        talentName: "The Heatwave Reliever",
    },
    {
        number: "22",
        firstName: "Zack",
        lastName: "Phillips",
        position: "LHP",
        photo: "fire/Phillips.jpeg",
        talentName: "The Smokey Southpaw",
    },
    {
        number: "23",
        firstName: "Ron",
        lastName: "Franklin Jr.",
        position: "OF",
        photo: "fire/Franklin Jr..jpeg",
        talentName: "The Blaze Runner",
    },
    {
        number: "24",
        firstName: "Dakota",
        lastName: "McFadden",
        position: "UTL",
        photo: "fire/McFadden.jpeg",
        talentName: "The Dual-Threat Fireman",
    },
    {
        number: "25",
        firstName: "Ga’Von",
        lastName: "Wray",
        position: "RHP",
        photo: "fire/Wray.jpeg",
        talentName: "The Delivery Engine",
    },
    {
        number: "27",
        firstName: "Val",
        lastName: "Perez",
        position: "Head Coach",
        photo: "fire/Perez.jpeg",
        talentName: "The Fire Chief",
    },
    {
        number: "29",
        firstName: "Brian",
        lastName: "Trepanier",
        position: "P",
        photo: "fire/Trepanier.jpeg",
        talentName: "The Siren Slinger",
    },
    {
        number: "30",
        firstName: "Armando",
        lastName: "Becerra",
        position: "OF",
        photo: "fire/Becerra.jpeg",
        talentName: "The Spark Plug",
    },
    {
        number: "37",
        firstName: "Blake",
        lastName: "Morgan",
        position: "LHP",
        photo: "fire/Morgan.jpeg",
        talentName: "The Freeze Pitcher",
    },
    {
        number: "42",
        firstName: "Bradford",
        lastName: "Webb",
        position: "RHP",
        photo: "fire/Webb.jpeg",
        talentName: "The Flip-Pitch Trickster",
    },
    {
        number: "55",
        firstName: "Tyner",
        lastName: "Hughes",
        position: "UTL",
        photo: "fire/Hughes.jpeg",
        talentName: "The Engine Utility",
    },
    {
        number: "95",
        firstName: "Johnny",
        lastName: "Hummel",
        position: "RHP",
        photo: "fire/Hummel.jpeg",
        talentName: "The Rocket Launcher",
    },
];

// texas
const texas = [
    {
        number: "",
        firstName: "Joe",
        lastName: "Mikulik",
        position: "Coach",
        photo: "texas/Mikulik.jpeg",
        talentName: "The Umpire Tormentor",
    },
    {
        number: "",
        firstName: "Brandon",
        lastName: "Pennington",
        position: "Assistant Coach",
        photo: "texas/Pennington.jpeg",
        talentName: "The Strategy General",
    },
    {
        number: "",
        firstName: "Andrew",
        lastName: "Bartman",
        position: "Assistant Coach",
        photo: "texas/Bartman.jpeg",
        talentName: "The Drill Architect",
    },
    {
        number: "1",
        firstName: "Jonathan",
        lastName: "Luders",
        position: "2B",
        photo: "texas/Luders.jpeg",
        talentName: "The Unicycle Juggler",
    },
    {
        number: "2",
        firstName: "Zach",
        lastName: "Watson",
        position: "UTL",
        photo: "texas/Watson.jpeg",
        talentName: "THe Launchpad Outfielder",
    },
    {
        number: "3",
        firstName: "Jayson",
        lastName: "Arendt",
        position: "OF/ENT",
        photo: "texas/Arendt.jpeg",
        talentName: "The Showman Swing",
    },
    {
        number: "5",
        firstName: "Jorden",
        lastName: "Hussein",
        position: "SS",
        photo: "texas/Hussein.jpeg",
        talentName: "THe Smooth Operator SS",
    },
    {
        number: "6",
        firstName: "Jordan",
        lastName: "Barth",
        position: "INF",
        photo: "texas/Barth.jpeg",
        talentName: "The Hot-Corner Anchor",
    },
    {
        number: "7",
        firstName: "Indiana",
        lastName: "Stanley",
        position: "UTL",
        photo: "texas/Stanley.jpeg",
        talentName: "The Utility Swiss Army",
    },
    {
        number: "8",
        firstName: "Jonathan",
        lastName: "Hughes",
        position: "RHP",
        photo: "texas/Hughes.jpeg",
        talentName: "The Opening-Day Fireballer",
    },
    {
        number: "9",
        firstName: "Nick",
        lastName: "Lopez",
        position: "UTL",
        photo: "texas/Lopez.jpeg",
        talentName: "The Iron-Utility",
    },
    {
        number: "11",
        firstName: "Mac",
        lastName: "Danford",
        position: "1B",
        photo: "texas/Danford.jpeg",
        talentName: "The Muscle Firstman",
    },
    {
        number: "12",
        firstName: "Christian",
        lastName: "Davis",
        position: "LHP",
        photo: "texas/Davis.jpeg",
        talentName: "The Smokey Southpaw",
    },
    {
        number: "16",
        firstName: "Travis",
        lastName: "Moniot",
        position: "3B",
        photo: "texas/Moniot.jpeg",
        talentName: "The Trick Thirdman",
    },
    {
        number: "17",
        firstName: "Brett",
        lastName: "Sanchez",
        position: "RHP",
        photo: "texas/Sanchez.jpeg",
        talentName: "The McAllen Missile",
    },
    {
        number: "22",
        firstName: "Reese",
        lastName: "Miller",
        position: "RHP",
        photo: "texas/Miller.jpeg",
        talentName: "The Shutout Slinger",
    },
    {
        number: "23",
        firstName: "Joe",
        lastName: "Sperone",
        position: "RHP",
        photo: "texas/Sperone.jpeg",
        talentName: "The Cheese Chucker",
    },
    {
        number: "24",
        firstName: "Jon",
        lastName: "Reid",
        position: "LHP",
        photo: "texas/Reid.jpeg",
        talentName: "The Pro-Stripe Lefty",
    },
    {
        number: "26",
        firstName: "Taj",
        lastName: "Porter",
        position: "C",
        photo: "texas/Porter.jpeg",
        talentName: "The HBCU Swagger Backstop",
    },
    {
        number: "27",
        firstName: "Kyle",
        lastName: "Martin",
        position: "OF/1B",
        photo: "texas/Martin.jpeg",
        talentName: "The Border-to-Border Blast",
    },
    {
        number: "28",
        firstName: "Jose",
        lastName: "Gonzalez",
        position: "OF/1B",
        photo: "texas/Gonzalez.jpeg",
        talentName: "The Deep-Drive King",
    },
    {
        number: "29",
        firstName: "Tyler",
        lastName: "Rigot",
        position: "LHP",
        photo: "texas/Rigot.jpeg",
        talentName: "The Batter-Blaster Lefty",
    },
    {
        number: "33",
        firstName: "Tre",
        lastName: "Jones",
        position: "DR/ENT",
        photo: "texas/Jones.jpeg",
        talentName: "The Tailgate Hype-Man",
    },
    {
        number: "34",
        firstName: "Megan",
        lastName: "Wiggins",
        position: "OF",
        photo: "texas/Wiggins.jpeg",
        talentName: "The Softball Royalty",
    },
    {
        number: "36",
        firstName: "Brett",
        lastName: "Allen",
        position: "RHP",
        photo: "texas/Allen.jpeg",
        talentName: "The Delivery Chameleon",
    },
    {
        number: "37",
        firstName: "Zach",
        lastName: "Blankenship",
        position: "LHP",
        photo: "texas/Blankenship.jpeg",
        talentName: "The Baseline Freeze",
    },
    {
        number: "44",
        firstName: "Chris",
        lastName: "Clarke",
        position: "RHP",
        photo: "texas/Clarke.jpeg",
        talentName: "The Heavy-SInk Righty",
    },
    {
        number: "85",
        firstName: "Taylor",
        lastName: "Justus",
        position: "C",
        photo: "texas/Justus.jpeg",
        talentName: "The Plate General",
    },
    {
        number: "99",
        firstName: "Jimmy",
        lastName: "Lewis",
        position: "RHP",
        photo: "texas/Lewis.jpeg",
        talentName: "The Strikeout Jester",
    },
];

// coco
const coco = [
    {
        number: "",
        firstName: "Mark",
        lastName: "Crocco",
        position: "Coach",
        photo: "coco/Crocco.jpeg",
        talentName: "The Dugout Director",
    },
    {
        number: "",
        firstName: "Shane",
        lastName: "Victorino",
        position: "Primetime Coach",
        photo: "coco/Victorino.jpeg",
        talentName: "The Flyin' Hawaiian",
    },
    {
        number: "",
        firstName: "Anthony",
        lastName: "Marks",
        position: "Assistant Coach",
        photo: "coco/Marks.jpeg",
        talentName: "THe Outfield Architect",
    },
    {
        number: "",
        firstName: "Endy",
        lastName: "Morales",
        position: "Assistant Coach",
        photo: "coco/Morales.jpeg",
        talentName: "The Strategic Co-Pilot",
    },
    {
        number: "0",
        firstName: "CJ",
        lastName: "Williams",
        position: "RHP",
        photo: "coco/Williams.jpeg",
        talentName: "The Ground-Zero Reliever",
    },
    {
        number: "1",
        firstName: "Peyton",
        lastName: "Chatagnier",
        position: "INF",
        photo: "coco/Chatagnier.jpeg",
        talentName: "The High-Octane Infielder",
    },
    {
        number: "2",
        firstName: "Sal",
        lastName: "Jacobo",
        position: "INF",
        photo: "coco/Jacobo.jpeg",
        talentName: "The Dirt-Diving Corner",
    },
    {
        number: "3",
        firstName: "Armani",
        lastName: "Henderson",
        position: "DR/ENT",
        photo: "coco/Henderson.jpeg",
        talentName: "The High-Fashion Speedster",
    },
    {
        number: "4",
        firstName: "Brett",
        lastName: "Carson",
        position: "LHP/OF/1B",
        photo: "coco/Carson.jpeg",
        talentName: "The Three-Way Weapon",
    },
    {
        number: "6",
        firstName: "Drake",
        lastName: "Fontenot",
        position: "RHP",
        photo: "coco/Fontenot.jpeg",
        talentName: "The Fire-Throwing Righty",
    },
    {
        number: "7",
        firstName: "JD",
        lastName: "Urso",
        position: "UTL",
        photo: "coco/Urso.jpeg",
        talentName: "The Everywhere Swiss Army",
    },
    {
        number: "8",
        firstName: "Kaden",
        lastName: "Bowler",
        position: "OF/ENT",
        photo: "coco/Bowler.jpeg",
        talentName: "The Dance-Party Outfielder",
    },
    {
        number: "9",
        firstName: "Ben",
        lastName: "Parker",
        position: "OF",
        photo: "coco/Parker.jpeg",
        talentName: "The Fly-Robbing Jet",
    },
    {
        number: "10",
        firstName: "Tanner",
        lastName: "Allen",
        position: "OF",
        photo: "coco/Allen.jpeg",
        talentName: "The Championship Swing",
    },
    {
        number: "11",
        firstName: "Ashby",
        lastName: "Vining",
        position: "C",
        photo: "coco/Vining.jpeg",
        talentName: "The Backstop Guardian",
    },
    {
        number: "12",
        firstName: "Keegan",
        lastName: "James",
        position: "RHP",
        photo: "coco/James.jpeg",
        talentName: "The Lockdown Slinger",
    },
    {
        number: "13",
        firstName: "Dalton",
        lastName: "Mauldin",
        position: "UTL",
        photo: "coco/Mauldin.jpeg",
        talentName: "The Utility Dynamo",
    },
    {
        number: "15",
        firstName: "Jordan",
        lastName: "Brewer",
        position: "1B/OF",
        photo: "coco/Brewer.jpeg",
        talentName: "The Launchpad Power",
    },
    {
        number: "17",
        firstName: "Blake",
        lastName: "Benson",
        position: "LHP/ENT",
        photo: "coco/Benson.jpeg",
        talentName: "The Southpaw Performer",
    },
    {
        number: "18",
        firstName: "Gideon",
        lastName: "Antle",
        position: "OF",
        photo: "coco/Antle.jpeg",
        talentName: "The Grass Patrolman",
    },
    {
        number: "19",
        firstName: "Zach",
        lastName: "Smith",
        position: "RHP",
        photo: "coco/Smith.jpeg",
        talentName: "The Slider Technician",
    },
    {
        number: "20",
        firstName: "Will",
        lastName: "Ethridge",
        position: "RHP",
        photo: "coco/Ethridge.jpeg",
        talentName: "The Heavy-Sink Righty",
    },
    {
        number: "21",
        firstName: "Erik",
        lastName: "Ostberg",
        position: "C",
        photo: "coco/Ostberg.jpeg",
        talentName: "The High-Energy Backstop",
    },
    {
        number: "22",
        firstName: "Austin",
        lastName: "Krzeminski",
        position: "RHP",
        photo: "coco/Krzeminski.jpeg",
        talentName: "The Mound Jester",
    },
    {
        number: "23",
        firstName: "Dane",
        lastName: "Tofteland",
        position: "3B/1B",
        photo: "coco/Tofteland.jpeg",
        talentName: "The Corner Blast",
    },
    {
        number: "24",
        firstName: "Andy",
        lastName: "Archer",
        position: "RHP",
        photo: "coco/Archer.jpeg",
        talentName: "The Bullseye Righty",
    },
    {
        number: "30",
        firstName: "Joe",
        lastName: "Filomeno",
        position: "LHP",
        photo: "coco/Filomeno.jpeg",
        talentName: "The Fireman Southpaw",
    },
    {
        number: "31",
        firstName: "Grady",
        lastName: "Morgan",
        position: "OF",
        photo: "coco/Morgan.jpeg",
        talentName: "The Baseline Eraser",
    },
    {
        number: "1 of 1",
        firstName: "Kyle",
        lastName: "Perry",
        position: "LHP",
        photo: "coco/Perry.jpeg",
        talentName: "The One-of-a-Kind Lefty",
    },
    {
        number: "222",
        firstName: "Denae",
        lastName: "Benites",
        position: "C",
        photo: "coco/Benites.jpeg",
        talentName: "THe Tripple-Two Magician",
    },
];

// clowns
const clowns = [
    {
        number: "",
        firstName: "Errick",
        lastName: "Fox",
        position: "Head Coach",
        photo: "clowns/Fox.jpeg",

        talentName: "",
    },
    {
        number: "",
        firstName: "Ryan",
        lastName: "Howard",
        position: "Primetime Coach",
        photo: "clowns/Howard.jpeg",

        talentName: "",
    },
    {
        number: "",
        firstName: "Willie",
        lastName: "Carter",
        position: "Assistant Coach",
        photo: "clowns/Carter.jpeg",

        talentName: "",
    },
    {
        number: "",
        firstName: "Tony",
        lastName: "Voiro",
        position: "Assistant Coach",
        photo: "clowns/Voiro.jpeg",

        talentName: "",
    },
    {
        number: "1",
        firstName: "Kirkland",
        lastName: "Banks",
        position: "UTL",
        photo: "clowns/Banks.jpeg",

        talentName: "",
    },
    {
        number: "2",
        firstName: "Jalen",
        lastName: "Vosquez",
        position: "INF",
        photo: "clowns/Vosquez.jpeg",

        talentName: "",
    },
    {
        number: "3",
        firstName: "Joe",
        lastName: "Gray",
        position: "OF",
        photo: "clowns/Gray.jpeg",

        talentName: "",
    },
    {
        number: "4",
        firstName: "Gage",
        lastName: "Voorhees",
        position: "RHP",
        photo: "clowns/Voorhees.jpeg",

        talentName: "",
    },
    {
        number: "5",
        firstName: "Brian",
        lastName: "Dansereau",
        position: "OF",
        photo: "clowns/Dansereau.jpeg",

        talentName: "",
    },
    {
        number: "7",
        firstName: "Bobby",
        lastName: "Lada",
        position: "INF",
        photo: "clowns/Lada.jpeg",

        talentName: "",
    },
    {
        number: "8",
        firstName: "Brett",
        lastName: "Maddock",
        position: "RHP",
        photo: "clowns/Maddock.jpeg",

        talentName: "",
    },
    {
        number: "9",
        firstName: "Chris",
        lastName: "Burgess",
        position: "C",
        photo: "clowns/Burgess.jpeg",

        talentName: "",
    },
    {
        number: "11",
        firstName: "Correlle",
        lastName: "Prime",
        position: "RHP/INF",
        photo: "clowns/Prime.jpeg",

        talentName: "",
    },
    {
        number: "12",
        firstName: "Niko",
        lastName: "Hulsizer",
        position: "OF",
        photo: "clowns/Hulsizer.jpeg",

        talentName: "",
    },
    {
        number: "13",
        firstName: "Clark",
        lastName: "Gilmore",
        position: "RHP",
        photo: "clowns/Gilmore.jpeg",

        talentName: "",
    },
    {
        number: "15",
        firstName: "David",
        lastName: "Griffin",
        position: "RHP",
        photo: "clowns/Griffin.jpeg",

        talentName: "",
    },
    {
        number: "16",
        firstName: "Eli",
        lastName: "Paton",
        position: "INF",
        photo: "clowns/Paton.jpeg",

        talentName: "",
    },
    {
        number: "19",
        firstName: "Jackie",
        lastName: "Bradley Jr.",
        position: "OF",
        photo: "clowns/Bradley Jr..jpeg",

        talentName: "",
    },
    {
        number: "21",
        firstName: "Vinny",
        lastName: "Santarseiro",
        position: "RHP",
        photo: "clowns/Santarseiro.jpeg",

        talentName: "",
    },
    {
        number: "22",
        firstName: "Joes",
        lastName: "Lytle",
        position: "C",
        photo: "clowns/Lytle.jpeg",

        talentName: "",
    },
    {
        number: "24",
        firstName: "Kobe",
        lastName: "Robinson",
        position: "RHP",
        photo: "clowns/Robinson.jpeg",

        talentName: "",
    },
    {
        number: "25",
        firstName: "Dayan",
        lastName: "Reinoso",
        position: "RHP",
        photo: "clowns/Reinoso.jpeg",

        talentName: "",
    },
    {
        number: "33",
        firstName: "Nick",
        lastName: "Wilson",
        position: "RHP",
        photo: "clowns/Wilson.jpeg",

        talentName: "",
    },
    {
        number: "34",
        firstName: "Daniel",
        lastName: "Foster",
        position: "LHP",
        photo: "clowns/Foster.jpeg",

        talentName: "",
    },
    {
        number: "44",
        firstName: "Dale",
        lastName: "Francis Jr.",
        position: "UTL",
        photo: "clowns/Francis Jr..jpeg",

        talentName: "",
    },
    {
        number: "67",
        firstName: "Andrew",
        lastName: "Irvine",
        position: "RHP",
        photo: "clowns/Irvine.jpeg",

        talentName: "",
    },
    {
        number: "!",
        firstName: "Matt",
        lastName: "Wolf",
        position: "RHP/2B/ENT",
        photo: "clowns/Wolf.jpeg",

        talentName: "",
    },
    {
        number: "∞",
        firstName: "Fisher",
        lastName: "Polydoroff",
        position: "RHP/EH/ENT",
        photo: "clowns/Polydoroff.jpeg",

        talentName: "",
    },
    {
        number: "🗲",
        firstName: "Malachi",
        lastName: "Mitchell",
        position: "EH/DR",
        photo: "clowns/Mitchell.jpeg",

        talentName: "",
    },
];

// check to make sure the array is properly defined and accessible
console.log(savannah);
console.log(savannah[0]);