//savannah players
const savannah = [
    {
        number: "1",
        firstName: "Bill",
        lastName: "LeRoy",
        position: "C",
        photo: "savannah/LeRoy.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "2",
        firstName: "Reese",
        lastName: "Alexiades",
        position: "OF",
        photo: "savannah/Alexiades.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "3",
        firstName: "Bryce",
        lastName: "Grizzaffi",
        position: "C",
        photo: "savannah/Grizzaffi.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "4",
        firstName: "KJ",
        lastName: "Jackson",
        position: "UTL",
        photo: "savannah/KJ.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "5",
        firstName: "DR",
        lastName: "Meadows",
        position: "OF",
        photo: "savannah/Meadows.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "6",
        firstName: "Ryan",
        lastName: "Cox",
        position: "SS",
        photo: "savannah/Cox.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "7",
        firstName: "Ty",
        lastName: "Jackson",
        position: "OF",
        photo: "savannah/Ty.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "8",
        firstName: "Jackson",
        lastName: "Olson",
        position: "INF",
        photo: "savannah/Olson.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "9",
        firstName: "Max",
        lastName: "Jung-Goldberg",
        position: "UTL",
        photo: "savannah/Jung-Goldberg.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "10",
        firstName: "Alex",
        lastName: "Ziegler",
        position: "1B",
        photo: "savannah/Ziegler.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "11",
        firstName: "Austin",
        lastName: "Drury",
        position: "P",
        photo: "savannah/Drury.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "12",
        firstName: "Kyle",
        lastName: "Luigs",
        position: "P",
        photo: "savannah/Luigs.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "13",
        firstName: "Bryce",
        lastName: "Stober",
        position: "Coach",
        photo: "savannah/Stober.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "14",
        firstName: "Dakota",
        lastName: "Albritton",
        position: "UTL",
        photo: "savannah/Albritton.jpeg",
        funFact: "Enjoys spaghetti with ranch",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "15",
        firstName: "RobertAnthony",
        lastName: "Cruz",
        position: "OF",
        photo: "savannah/Cruz.jpeg",
        funFact: "Was homeschooled most of his life.",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "16",
        firstName: "Adam",
        lastName: "Virant",
        position: "Coach",
        photo: "savannah/Virant.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
    {
        number: "17",
        firstName: "Easton",
        lastName: "Parrish",
        position: "C",
        photo: "savannah/Parrish.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "18",
        firstName: "Danny",
        lastName: "Hosley",
        position: "UTL",
        photo: "savannah/Hosley.jpeg",
        funFact: "Certified EMT",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "19",
        firstName: "Dan",
        lastName: "Oberst",
        position: "DH",
        photo: "savannah/Oberst.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "20",
        firstName: "Grant",
        lastName: "Besser",
        position: "P",
        photo: "savannah/Besser.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "21",
        firstName: "Jacob",
        lastName: "Bazala",
        position: "P",
        photo: "savannah/Bazala.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "22",
        name: "JT Sokolove",
        position: "DR",
        photo: "savannah/Sokolove.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "23",
        firstName: "Reginald",
        lastName: "Horton",
        position: "Inspiration Coach",
        photo: "savannah/Horton.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "24",
        firstName: "Derek",
        lastName: "Klena",
        position: "RHP",
        photo: "savannah/Klena.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "30",
        firstName: "Connor",
        lastName: "Harris",
        position: "P",
        photo: "savannah/Harris.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "31",
        firstName: "Trystan",
        lastName: "Levesque",
        position: "P",
        photo: "savannah/Levesque.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "33",
        firstName: "Kelsie",
        lastName: "Whitmore",
        position: "P",
        photo: "savannah/Whitmore.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "44",
        firstName: "Allan",
        lastName: "Saathoff",
        position: "P",
        photo: "savannah/Saathoff.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "49",
        firstName: "Ryan",
        lastName: "Kellogg",
        position: "P Coach",
        photo: "savannah/Kellogg.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "66",
        firstName: "Tyler",
        lastName: "Gillum",
        position: "Head Coach",
        photo: "savannah/Gillum.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "88",
        firstName: "Noah",
        lastName: "Niznik",
        position: "P",
        photo: "savannah/Niznik.jpeg",
        funFact: "Loves Mariah Carey",
        talent: "Trick throw-downs from the catcher position",
    }, {
        number: "99",
        firstName: "Frankie",
        lastName: "Moscatiello",
        position: "P",
        photo: "savannah/Moscatiello.jpeg",
        funFact: "Excellent Breakfast Chef",
        talent: "Trick throw-downs from the catcher position",
    },
];


//party players
const party = [
    {
        number: "0",
        firstName: "Thomas",
        lastName: "Simoneaux",
        position: "Coach",
        photo: "party/Simoneaux.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "1",
        firstName: "Ashton",
        lastName: "Lansdell",
        position: "2B",
        photo: "party/Lansdell.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "2",
        firstName: "Jason",
        lastName: "Swan",
        position: "1B",
        photo: "party/Swan.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "3",
        firstName: "TJ",
        lastName: "Reeves",
        position: "OF",
        photo: "party/Reeves.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "4",
        firstName: "Tanner",
        lastName: "Thomas",
        position: "OF",
        photo: "party/Thomas.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "5",
        firstName: "Andy",
        lastName: "Cosgrove",
        position: "C",
        photo: "party/Cosgrove.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "6",
        firstName: "Reece",
        lastName: "Hampton",
        position: "OF",
        photo: "party/Hampton.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "7",
        firstName: "Mike",
        lastName: "Vavasis",
        position: "Head Coach",
        photo: "party/Vavasis.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "8",
        firstName: "Bryson",
        lastName: "Bloomer",
        position: "3B",
        photo: "party/Bloomer.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "9",
        firstName: "Dustin",
        lastName: "Baber",
        position: "2B",
        photo: "party/Baber.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "10",
        firstName: "Bret",
        lastName: "Helton",
        position: "RHP",
        photo: "party/Helton.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "11",
        firstName: "Chase",
        lastName: "Achuff",
        position: "SS",
        photo: "party/Achuff.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "12",
        firstName: "Noah",
        lastName: "Fisher",
        position: "UTL",
        photo: "party/Fisher.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "13",
        firstName: "Brady",
        lastName: "Kais",
        position: "LHP",
        photo: "party/Kais.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "15",
        firstName: "Dylan",
        lastName: "Porter",
        position: "RHP",
        photo: "party/Porter.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "17",
        firstName: "Dalton",
        lastName: "Ponce",
        position: "RHP",
        photo: "party/Ponce.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "21",
        firstName: "Riyan",
        lastName: "Rodriguez",
        position: "RHP",
        photo: "party/Rodriguez.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "22",
        firstName: "Peter",
        lastName: "Holden",
        position: "LHP",
        photo: "party/Holden.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "25",
        firstName: "Sean",
        lastName: "Fluke",
        position: "RHP",
        photo: "party/Fluke.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "26",
        firstName: "Nate",
        lastName: "Tellier",
        position: "RHP",
        photo: "party/Tellier.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "27",
        firstName: "Jake",
        lastName: "Lialios",
        position: "RHP",
        photo: "party/Lialios.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "28",
        firstName: "Drew",
        lastName: "Gillespie",
        position: "RHP",
        photo: "party/Gillespie.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "40",
        firstName: "Mark",
        lastName: "Smith",
        position: "DR",
        photo: "party/Smith.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "41",
        firstName: "Bronson",
        lastName: "Balholm",
        position: "C",
        photo: "party/Balholm.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "57",
        firstName: "Anthony",
        lastName: "Coromato",
        position: "Coach",
        photo: "party/Coromato.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "407",
        firstName: "Michael",
        lastName: "Ballard",
        position: "IF",
        photo: "party/Ballard.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "777",
        firstName: "Garrett",
        lastName: "Delano",
        position: "RHP",
        photo: "party/Delano.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "999",
        firstName: "John-Howard",
        lastName: "Bobo",
        position: "UTL",
        photo: "party/Bobo.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "X",
        firstName: "Jake",
        lastName: "Skole",
        position: "OF",
        photo: "party/Skole.jpeg",
        funFact: "",
        talent: "",
    },
];

//firefighter players
const fire = [
    {
        number: "🔥",
        firstName: "Marshall",
        lastName: "Shill",
        position: "RHP",
        photo: "fire/Shill.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "0",
        firstName: "Lamar",
        lastName: "Sparks",
        position: "OF",
        photo: "fire/Sparks.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "1",
        firstName: "Christian",
        lastName: "Dearman",
        position: "RHP",
        photo: "fire/Dearman.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "2",
        firstName: "Caden",
        lastName: "Green",
        position: "SS",
        photo: "fire/Green.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "3",
        firstName: "Dalton",
        lastName: "Cornett",
        position: "C",
        photo: "fire/Cornett.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "3.14",
        firstName: "Corey",
        lastName: "Pye",
        position: "Pitching Coach",
        photo: "fire/Pye.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "4",
        firstName: "Eric",
        lastName: "Jones Jr.",
        position: "C/1B",
        photo: "fire/Jones Jr..jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "6",
        firstName: "Austin",
        lastName: "Temple",
        position: "RHP",
        photo: "fire/Temple.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "7",
        firstName: "Mason",
        lastName: "Maxwell",
        position: "OF",
        photo: "fire/Maxwell.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "8",
        firstName: "South",
        lastName: "Trimble",
        position: "DR",
        photo: "fire/Trimble.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "9",
        firstName: "Noah",
        lastName: "Bridges",
        position: "OF",
        photo: "fire/Bridges.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "10",
        firstName: "Darrien",
        lastName: "",
        position: "1B/OF",
        photo: "fire/Darrien.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "11",
        firstName: "Logan",
        lastName: "Lacey",
        position: "3B",
        photo: "fire/Lacey.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "12",
        firstName: "Zachary",
        lastName: "Bridges",
        position: "C",
        photo: "fire/Bridges.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "15",
        firstName: "Liam",
        lastName: "Spence",
        position: "INF",
        photo: "fire/Spence.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "16",
        firstName: "Drew",
        lastName: "Yniesta",
        position: "Assistant Coach",
        photo: "fire/Yniesta.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "18",
        firstName: "Ben",
        lastName: "Dum III",
        position: "RHP",
        photo: "fire/Dum III.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "21",
        firstName: "Jared",
        lastName: "Donalson",
        position: "RHP",
        photo: "fire/Donalson.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "22",
        firstName: "Zack",
        lastName: "Phillips",
        position: "LHP",
        photo: "fire/Phillips.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "23",
        firstName: "Ron",
        lastName: "Franklin Jr.",
        position: "OF",
        photo: "fire/Franklin Jr..jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "24",
        firstName: "Dakota",
        lastName: "McFadden",
        position: "UTL",
        photo: "fire/McFadden.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "25",
        firstName: "Ga’Von",
        lastName: "Wray",
        position: "RHP",
        photo: "fire/Wray.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "27",
        firstName: "Val",
        lastName: "Perez",
        position: "Head Coach",
        photo: "fire/Perez.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "29",
        firstName: "Brian",
        lastName: "Trepanier",
        position: "P",
        photo: "fire/Trepanier.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "30",
        firstName: "Armando",
        lastName: "Becerra",
        position: "OF",
        photo: "fire/Becerra.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "37",
        firstName: "Blake",
        lastName: "Morgan",
        position: "LHP",
        photo: "fire/Morgan.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "42",
        firstName: "Bradford",
        lastName: "Webb",
        position: "RHP",
        photo: "fire/Webb.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "55",
        firstName: "Tyner",
        lastName: "Hughes",
        position: "UTL",
        photo: "fire/Hughes.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "95",
        firstName: "Johnny",
        lastName: "Hummel",
        position: "RHP",
        photo: "fire/Hummel.jpeg",
        funFact: "",
        talent: "",
    },
];

// texas
const texas = [
    {
        number: "",
        firstName: "Joe",
        lastName: "Mikulik",
        position: "Coach",
        photo: "texas/Mikulik.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Brandon",
        lastName: "Pennington",
        position: "Assistant Coach",
        photo: "texas/Pennington.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Andrew",
        lastName: "Bartman",
        position: "Assistant Coach",
        photo: "texas/Bartman.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "1",
        firstName: "Jonathan",
        lastName: "Luders",
        position: "2B",
        photo: "texas/Luders.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "2",
        firstName: "Zach",
        lastName: "Watson",
        position: "UTL",
        photo: "texas/Watson.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "3",
        firstName: "Jayson",
        lastName: "Arendt",
        position: "OF/ENT",
        photo: "texas/Arendt.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "5",
        firstName: "Jorden",
        lastName: "Hussein",
        position: "SS",
        photo: "texas/Hussein.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "6",
        firstName: "Jordan",
        lastName: "Barth",
        position: "INF",
        photo: "texas/Barth.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "7",
        firstName: "Indiana",
        lastName: "Stanley",
        position: "UTL",
        photo: "texas/Stanley.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "8",
        firstName: "Jonathan",
        lastName: "Hughes",
        position: "RHP",
        photo: "texas/Hughes.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "9",
        firstName: "Nick",
        lastName: "Lopez",
        position: "UTL",
        photo: "texas/Lopez.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "11",
        firstName: "Mac",
        lastName: "Danford",
        position: "1B",
        photo: "texas/Danford.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "12",
        firstName: "Christian",
        lastName: "Davis",
        position: "LHP",
        photo: "texas/Davis.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "16",
        firstName: "Travis",
        lastName: "Moniot",
        position: "3B",
        photo: "texas/Moniot.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "17",
        firstName: "Brett",
        lastName: "Sanchez",
        position: "RHP",
        photo: "texas/Sanchez.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "22",
        firstName: "Reese",
        lastName: "Miller",
        position: "RHP",
        photo: "texas/Miller.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "23",
        firstName: "Joe",
        lastName: "Sperone",
        position: "RHP",
        photo: "texas/Sperone.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "24",
        firstName: "Jon",
        lastName: "Reid",
        position: "LHP",
        photo: "texas/Reid.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "26",
        firstName: "Taj",
        lastName: "Porter",
        position: "C",
        photo: "texas/Porter.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "27",
        firstName: "Kyle",
        lastName: "Martin",
        position: "OF/1B",
        photo: "texas/Martin.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "28",
        firstName: "Jose",
        lastName: "Gonzalez",
        position: "OF/1B",
        photo: "texas/Gonzalez.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "29",
        firstName: "Tyler",
        lastName: "Rigot",
        position: "LHP",
        photo: "texas/Rigot.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "33",
        firstName: "Tre",
        lastName: "Jones",
        position: "DR/ENT",
        photo: "texas/Jones.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "34",
        firstName: "Megan",
        lastName: "Wiggins",
        position: "OF",
        photo: "texas/Wiggins.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "36",
        firstName: "Brett",
        lastName: "Allen",
        position: "RHP",
        photo: "texas/Allen.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "37",
        firstName: "Zach",
        lastName: "Blankenship",
        position: "LHP",
        photo: "texas/Blankenship.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "44",
        firstName: "Chris",
        lastName: "Clarke",
        position: "RHP",
        photo: "texas/Clarke.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "85",
        firstName: "Taylor",
        lastName: "Justus",
        position: "C",
        photo: "texas/Justus.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "99",
        firstName: "Jimmy",
        lastName: "Lewis",
        position: "RHP",
        photo: "texas/Lewis.jpeg",
        funFact: "",
        talent: "",
    },
];

// coco
const coco = [
    {
        number: "",
        firstName: "Mark",
        lastName: "Crocco",
        position: "Coach",
        photo: "coco/Crocco.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Shane",
        lastName: "Victorino",
        position: "Primetime Coach",
        photo: "coco/Victorino.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Anthony",
        lastName: "Marks",
        position: "Assistant Coach",
        photo: "coco/Marks.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Endy",
        lastName: "Morales",
        position: "Assistant Coach",
        photo: "coco/Morales.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "0",
        firstName: "CJ",
        lastName: "Williams",
        position: "RHP",
        photo: "coco/Williams.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "1",
        firstName: "Peyton",
        lastName: "Chatagnier",
        position: "INF",
        photo: "coco/Chatagnier.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "2",
        firstName: "Sal",
        lastName: "Jacobo",
        position: "INF",
        photo: "coco/Jacobo.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "3",
        firstName: "Armani",
        lastName: "Henderson",
        position: "DR/ENT",
        photo: "coco/Henderson.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "4",
        firstName: "Brett",
        lastName: "Carson",
        position: "LHP/OF/1B",
        photo: "coco/Carson.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "6",
        firstName: "Drake",
        lastName: "Fontenot",
        position: "RHP",
        photo: "coco/Fontenot.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "7",
        firstName: "JD",
        lastName: "Urso",
        position: "UTL",
        photo: "coco/Urso.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "8",
        firstName: "Kaden",
        lastName: "Bowler",
        position: "OF/ENT",
        photo: "coco/Bowler.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "9",
        firstName: "Ben",
        lastName: "Parker",
        position: "OF",
        photo: "coco/Parker.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "10",
        firstName: "Tanner",
        lastName: "Allen",
        position: "OF",
        photo: "coco/Allen.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "11",
        firstName: "Ashby",
        lastName: "Vining",
        position: "C",
        photo: "coco/Vining.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "12",
        firstName: "Keegan",
        lastName: "James",
        position: "RHP",
        photo: "coco/James.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "13",
        firstName: "Dalton",
        lastName: "Mauldin",
        position: "UTL",
        photo: "coco/Mauldin.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "15",
        firstName: "Jordan",
        lastName: "Brewer",
        position: "1B/OF",
        photo: "coco/Brewer.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "17",
        firstName: "Blake",
        lastName: "Benson",
        position: "LHP/ENT",
        photo: "coco/Benson.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "18",
        firstName: "Gideon",
        lastName: "Antle",
        position: "OF",
        photo: "coco/Antle.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "19",
        firstName: "Zach",
        lastName: "Smith",
        position: "RHP",
        photo: "coco/Smith.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "20",
        firstName: "Will",
        lastName: "Ethridge",
        position: "RHP",
        photo: "coco/Ethridge.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "21",
        firstName: "Erik",
        lastName: "Ostberg",
        position: "C",
        photo: "coco/Ostberg.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "22",
        firstName: "Austin",
        lastName: "Krzeminski",
        position: "RHP",
        photo: "coco/Krzeminski.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "23",
        firstName: "Dane",
        lastName: "Tofteland",
        position: "3B/1B",
        photo: "coco/Tofteland.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "24",
        firstName: "Andy",
        lastName: "Archer",
        position: "RHP",
        photo: "coco/Archer.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "30",
        firstName: "Joe",
        lastName: "Filomeno",
        position: "LHP",
        photo: "coco/Filomeno.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "31",
        firstName: "Grady",
        lastName: "Morgan",
        position: "OF",
        photo: "coco/Morgan.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "1 of 1",
        firstName: "Kyle",
        lastName: "Perry",
        position: "LHP",
        photo: "coco/Perry.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "222",
        firstName: "Denae",
        lastName: "Benites",
        position: "C",
        photo: "coco/Benites.jpeg",
        funFact: "",
        talent: "",
    },
];

// clowns
const clowns = [
    {
        number: "",
        firstName: "Errick",
        lastName: "Fox",
        position: "Head Coach",
        photo: "clowns/Fox.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Ryan",
        lastName: "Howard",
        position: "Primetime Coach",
        photo: "clowns/Howard.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Willie",
        lastName: "Carter",
        position: "Assistant Coach",
        photo: "clowns/Carter.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "",
        firstName: "Tony",
        lastName: "Voiro",
        position: "Assistant Coach",
        photo: "clowns/Voiro.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "1",
        firstName: "Kirkland",
        lastName: "Banks",
        position: "UTL",
        photo: "clowns/Banks.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "2",
        firstName: "Jalen",
        lastName: "Vosquez",
        position: "INF",
        photo: "clowns/Vosquez.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "3",
        firstName: "Joe",
        lastName: "Gray",
        position: "OF",
        photo: "clowns/Gray.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "4",
        firstName: "Gage",
        lastName: "Voorhees",
        position: "RHP",
        photo: "clowns/Voorhees.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "5",
        firstName: "Brian",
        lastName: "Dansereau",
        position: "OF",
        photo: "clowns/Dansereau.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "7",
        firstName: "Bobby",
        lastName: "Lada",
        position: "INF",
        photo: "clowns/Lada.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "8",
        firstName: "Brett",
        lastName: "Maddock",
        position: "RHP",
        photo: "clowns/Maddock.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "9",
        firstName: "Chris",
        lastName: "Burgess",
        position: "C",
        photo: "clowns/Burgess.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "11",
        firstName: "Correlle",
        lastName: "Prime",
        position: "RHP/INF",
        photo: "clowns/Prime.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "12",
        firstName: "Niko",
        lastName: "Hulsizer",
        position: "OF",
        photo: "clowns/Hulsizer.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "13",
        firstName: "Clark",
        lastName: "Gilmore",
        position: "RHP",
        photo: "clowns/Gilmore.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "15",
        firstName: "David",
        lastName: "Griffin",
        position: "RHP",
        photo: "clowns/Griffin.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "16",
        firstName: "Eli",
        lastName: "Paton",
        position: "INF",
        photo: "clowns/Paton.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "19",
        firstName: "Jackie",
        lastName: "Bradley Jr.",
        position: "OF",
        photo: "clowns/Bradley Jr..jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "21",
        firstName: "Vinny",
        lastName: "Santarseiro",
        position: "RHP",
        photo: "clowns/Santarseiro.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "22",
        firstName: "Joes",
        lastName: "Lytle",
        position: "C",
        photo: "clowns/Lytle.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "24",
        firstName: "Kobe",
        lastName: "Robinson",
        position: "RHP",
        photo: "clowns/Robinson.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "25",
        firstName: "Dayan",
        lastName: "Reinoso",
        position: "RHP",
        photo: "clowns/Reinoso.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "33",
        firstName: "Nick",
        lastName: "Wilson",
        position: "RHP",
        photo: "clowns/Wilson.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "34",
        firstName: "Daniel",
        lastName: "Foster",
        position: "LHP",
        photo: "clowns/Foster.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "44",
        firstName: "Dale",
        lastName: "Francis Jr.",
        position: "UTL",
        photo: "clowns/Francis Jr..jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "67",
        firstName: "Andrew",
        lastName: "Irvine",
        position: "RHP",
        photo: "clowns/Irvine.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "!",
        firstName: "Matt",
        lastName: "Wolf",
        position: "RHP/2B/ENT",
        photo: "clowns/Wolf.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "∞",
        firstName: "Fisher",
        lastName: "Polydoroff",
        position: "RHP/EH/ENT",
        photo: "clowns/Polydoroff.jpeg",
        funFact: "",
        talent: "",
    },
    {
        number: "🗲",
        firstName: "Malachi",
        lastName: "Mitchell",
        position: "EH/DR",
        photo: "clowns/Mitchell.jpeg",
        funFact: "",
        talent: "",
    },
];

// check to make sure the array is properly defined and accessible
console.log(savannah);
console.log(savannah[0]);